### ISSUE TITLE
allow socket docker connection

### ISSUE THREAD

**Issue by anandkumarpatel** [CodeNow/docker-listener#4]
allow a socket connection to docker as well as http. using env

**Comment by podviaznikov** [comment]
@anandkumarpatel do you still want this feature?

Why do you want to have both socket and http?

**Comment by anandkumarpatel** [comment]
not a requirement now but would be nice to have in case we decide to run this externally and not in the dock.

**Comment by anandkumarpatel** [comment]
not needed, we want to move this off dock, so we need to use http
