### ISSUE TITLE
Docker inspect refactoring discussion/questions

### ISSUE THREAD

**Issue by podviaznikov** [CodeNow/docker-listener#56]
Currently we are trying to call `docker inspect` on appropriate containers to enhance payload with additional docker data.

I see several potential (or real?) problems with our current code.
1. multiple `docker inspect` commands might be run concurrently giving hard time to the docker daemon.
2. if we stop/restart/redeploy docker-listener while it was inspecting some events those events would never be published to rabbit and we will have inconsistent state between dock and mongo

Am I correct about this potential issues?

Potential solution:
Use RabbitMQ. When we receive docker-event we need to publish it to RabbitMQ.
Docker-listener will pick job from queue and try to enhance container.
If we use "prefetch" option we would be able to control amount of concurrent `docker inspect` calls(solves problem 1).
Since jobs will be in the RabbitMQ problem 2 will be improved, since docker-listener would be able to pick jobs.

Open questions:
1. We don't want to call docker.inspect from places other than docker-listener. Am I correct about that? We still doing it in few places: https://github.com/CodeNow/api/blob/master/lib/workers/stop-instance-container.js#L92.
2. When we are redeploying docker-listener now docker-listener service will be stopped and all unfinished job will be lost? E.x. if we were in the process of sending event to RabbitMQ it will be lost?

**Comment by podviaznikov** [comment]
@anandkumarpatel I came up with few questions while working on one API bug. Can you please read and comment?

**Comment by anandkumarpatel** [comment]
> 1. multiple docker inspect commands might be run concurrently giving hard time to the docker daemon.

inspect is a lightweight operation and should be fine to run 1000's of time

> 1. if we stop/restart/redeploy docker-listener while it was inspecting some events those events would never be published to rabbit and we will have inconsistent state between dock and mongo

correct, docker has an option to do polling. that is what swarm does, it gets events since X. we can do a hybrid solutions like save last timestamp to some database  and always do tail from that time, or something like that, this is a solved problem, a little research into how others fixed this will help 

> 1. We don't want to call docker.inspect from places other than docker-listener. Am I correct about that? We still doing it in few places: https://github.com/CodeNow/api/blob/master/lib/workers/stop-instance-container.js#L92.

yes, we need to remove that

> 1. When we are redeploying docker-listener now docker-listener service will be stopped and all unfinished job will be lost? E.x. if we were in the process of sending event to RabbitMQ it will be lost?

correct, we will lose all in progress publishes

**Comment by podviaznikov** [comment]
I think we addressed this one
